@HostAddress = https://localhost:7063



GET {{HostAddress}}/api/restaurants

###

GET {{HostAddress}}/api/restaurants/4

###

POST {{HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Tasty Bites",
  "Description": "A culinary experience like no other",
  "Category": "International Cuisine",
  "HasDelivery": true,
  "ContactEmail": "info@tastybites.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "123 Main Styreet",
  "PostalCode": "13-006"
}

###

