@HostAddress = https://localhost:7063



GET {{HostAddress}}/api/restaurants

###

GET {{HostAddress}}/api/restaurants/1

###

POST {{HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Jadfy Tasty",
  "Description": "A culinary Naija experience like no other",
  "Category": "African",
  "HasDelivery": true,
  "ContactEmail": "foody@jadefy.com",
  "ContactNumber": "5165-1234",
  "City": "Lagos",
  "Street": "A423 Main Island",
  "PostalCode": "63-006"
}

###


DELETE {{HostAddress}}/api/restaurants/1006

###

PATCH {{HostAddress}}/api/restaurants/1005
Content-Type: application/json

{
  "Name": "Jadfy Tasty",
  "Description": "A culinary Naija experience like no other",
  "HasDelivery": true
}


###
